- hosts: master
  become: yes
  tasks:
    - name: Install Docker, kubeadm, kubelet, kubectl
      shell: |
        yum update -y
        yum install -y docker
        systemctl enable --now docker
        setenforce 0
        sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
        cat <<EOF | tee /etc/yum.repos.d/kubernetes.repo
        [kubernetes]
        name=Kubernetes
        baseurl=https://pkgs.k8s.io/core:/stable:/v1.29/rpm/
        enabled=1
        gpgcheck=1
        gpgkey=https://pkgs.k8s.io/core:/stable:/v1.29/rpm/repodata/repomd.xml.key
        exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni
        EOF
        yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
        systemctl enable --now kubelet
        kubeadm init --apiserver-advertise-address={{ ansible_default_ipv4.address }} --pod-network-cidr=192.168.0.0/16

    - name: Configure kubectl for ec2-user
      shell: |
        mkdir -p /home/ec2-user/.kube
        cp -i /etc/kubernetes/admin.conf /home/ec2-user/.kube/config
        chown ec2-user:ec2-user /home/ec2-user/.kube/config

    - name: Install Calico CNI
      become_user: ec2-user
      shell: |
        curl -O https://raw.githubusercontent.com/projectcalico/calico/v3.29.0/manifests/calico.yaml
        kubectl apply -f calico.yaml

    - name: Wait for Kubernetes API server
      become_user: ec2-user
      shell: |
        until kubectl get nodes; do sleep 5; done

    - name: Get kubeadm join command
      shell: kubeadm token create --print-join-command
      register: join_cmd

    - name: Save join command to file
      copy:
        content: "{{ join_cmd.stdout }}"
        dest: /tmp/kubeadm_join.sh
        mode: 0755

    - name: Set fact for join command
      set_fact:
        kubeadm_join_command: "{{ join_cmd.stdout }}"
