- hosts: workers
  become: yes
  tasks:
    - name: Install Docker, kubeadm, kubelet
      shell: |
        yum update -y
        yum install -y docker
        systemctl enable --now docker
        setenforce 0 || true
        sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
        cat <<EOF | tee /etc/yum.repos.d/kubernetes.repo
        [kubernetes]
        name=Kubernetes
        baseurl=https://pkgs.k8s.io/core:/stable:/v1.29/rpm/
        enabled=1
        gpgcheck=1
        gpgkey=https://pkgs.k8s.io/core:/stable:/v1.29/rpm/repodata/repomd.xml.key
        exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni
        EOF
        yum install -y kubelet kubeadm --disableexcludes=kubernetes
        systemctl enable --now kubelet

    - name: Join worker to cluster
      shell: "{{ kubeadm_join_command }}"
      args:
        executable: /bin/bash
