---
- hosts: workers
  become: yes
  tasks:
    - name: Install Docker, kubeadm, kubelet
      yum:
        name:
          - docker
          - kubelet
          - kubeadm
        state: present
        enablerepo: kubernetes
        disable_excludes: kubernetes
        update_cache: yes

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Disable SELinux
      selinux:
        state: permissive

    - name: Enable and start kubelet
      systemd:
        name: kubelet
        enabled: yes
        state: started

    - name: Join worker node to cluster
      shell: "{{ kubeadm_join_command }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
      register: join_result
      until: join_result is succeeded
      retries: 5
      delay: 10